//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_CanBoCNV
    {
        public string MaTruong { get; set; }
        public string NamHoc { get; set; }
        public string Loai { get; set; }
        public Nullable<int> TongSo { get; set; }
        public Nullable<int> Nu { get; set; }
        public string DanToc { get; set; }
        public Nullable<int> DatChuan { get; set; }
        public Nullable<int> TrenChuan { get; set; }
        public Nullable<int> ChuaDatChuan { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> STT { get; set; }
    }
}
