//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_DuKienMinhChung
    {
        public string MaTruong { get; set; }
        public string NamHoc { get; set; }
        public string IDTieuChi { get; set; }
        public string DuKienMC { get; set; }
        public string NoiThuThap { get; set; }
        public string Nhom { get; set; }
        public string CaNhan { get; set; }
        public string Tuan { get; set; }
        public Nullable<System.DateTime> TuNgay { get; set; }
        public Nullable<System.DateTime> DenNgay { get; set; }
        public Nullable<decimal> ChiPhi { get; set; }
        public string GhiChu { get; set; }
    }
}
