//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_DanhGiaTieuChi
    {
        public string MaTruong { get; set; }
        public string IDTieuChi { get; set; }
        public string NamHoc { get; set; }
        public string MoTaHienTrang { get; set; }
        public string DiemManh { get; set; }
        public string DiemYeu { get; set; }
        public string NhanXetPGD { get; set; }
        public string KeHoachCaiTien { get; set; }
        public string MaNhom { get; set; }
        public Nullable<bool> PGDDuyet { get; set; }
        public Nullable<bool> TuDanhGia { get; set; }
    }
}
