//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_HocSinhNamHoc
    {
        public string MaTruong { get; set; }
        public string NamHoc { get; set; }
        public string LopHoc { get; set; }
        public Nullable<int> SoLuong { get; set; }
    }
}
