//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_HocSinhTHCS
    {
        public string MaTruong { get; set; }
        public string NamHoc { get; set; }
        public Nullable<int> Lop6 { get; set; }
        public Nullable<int> Lop7 { get; set; }
        public Nullable<int> Lop8 { get; set; }
        public Nullable<int> Lop9 { get; set; }
        public Nullable<int> Nu { get; set; }
        public Nullable<int> DanToc { get; set; }
        public Nullable<int> ChinhSach { get; set; }
        public Nullable<int> KhuyetTat { get; set; }
        public Nullable<int> TuyenMoi { get; set; }
        public Nullable<int> LuuBan { get; set; }
        public Nullable<int> BoHoc { get; set; }
        public Nullable<int> HaiBuoi { get; set; }
        public Nullable<int> BanTru { get; set; }
        public Nullable<int> NoiTru { get; set; }
        public Nullable<int> TotNghiep { get; set; }
        public Nullable<int> TotNghiepNu { get; set; }
        public Nullable<int> TotNghiepDT { get; set; }
        public Nullable<int> GioiCapHuyen { get; set; }
        public Nullable<int> GioiCapTinh { get; set; }
        public Nullable<int> GioiCapQG { get; set; }
    }
}
