//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_HocSinhMN
    {
        public string MaTruong { get; set; }
        public string NamHoc { get; set; }
        public Nullable<int> Col1 { get; set; }
        public Nullable<int> Col2 { get; set; }
        public Nullable<int> Col3 { get; set; }
        public Nullable<int> Col4 { get; set; }
        public Nullable<int> Col5 { get; set; }
        public Nullable<int> Col6 { get; set; }
        public Nullable<int> Nu { get; set; }
        public Nullable<int> DanToc { get; set; }
        public Nullable<int> ChinhSach { get; set; }
        public Nullable<int> KhuyetTat { get; set; }
        public Nullable<int> TuyenMoi { get; set; }
        public Nullable<int> HaiBuoi { get; set; }
        public Nullable<int> BanTru { get; set; }
    }
}
