//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_LopHocMN
    {
        public string MaTruong { get; set; }
        public string NamHoc { get; set; }
        public Nullable<int> Col1 { get; set; }
        public Nullable<int> Col2 { get; set; }
        public Nullable<int> Col3 { get; set; }
        public Nullable<int> Col4 { get; set; }
        public Nullable<int> Col5 { get; set; }
        public Nullable<int> Col6 { get; set; }
        public Nullable<int> Col7 { get; set; }
        public Nullable<int> Col8 { get; set; }
        public Nullable<int> Col9 { get; set; }
        public Nullable<int> Col10 { get; set; }
    }
}
