//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_MinhChung
    {
        public string MaTruong { get; set; }
        public string NamHoc { get; set; }
        public string MaMC { get; set; }
        public string TenMC { get; set; }
        public string SoHieu { get; set; }
        public string CoQuan { get; set; }
        public string GhiChu { get; set; }
        public string LinkFile { get; set; }
        public string TieuChuan { get; set; }
        public string TieuChi { get; set; }
    }
}
