//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_QuyDinh
    {
        public string ID { get; set; }
        public string SoHieu { get; set; }
        public string TenQuyDinh { get; set; }
        public Nullable<System.DateTime> NgayBanHanh { get; set; }
        public string CoQuan { get; set; }
        public string LinkFile { get; set; }
        public Nullable<bool> ApDung { get; set; }
        public string IDCapHoc { get; set; }
    }
}
