//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_ThongTinChung
    {
        public string MaTruong { get; set; }
        public string NamHoc { get; set; }
        public string IDCapHoc { get; set; }
        public string TenTruongMoi { get; set; }
        public string TenTruongCu { get; set; }
        public string CoQuanChuQuan { get; set; }
        public string TinhThanh { get; set; }
        public string QuanHuyen { get; set; }
        public string PhuongXa { get; set; }
        public string HieuTruong { get; set; }
        public string DienThoai { get; set; }
        public string Fax { get; set; }
        public string ChuanQuocGia { get; set; }
        public string Website { get; set; }
        public string NamThanhLap { get; set; }
        public Nullable<int> SoDiemTruong { get; set; }
        public string Loai { get; set; }
        public Nullable<bool> VungKhoKhan { get; set; }
        public Nullable<bool> LienKetNuocNgoai { get; set; }
        public Nullable<bool> Khac { get; set; }
        public string GhiChuKhac { get; set; }
        public string Code { get; set; }
        public string DiaChi { get; set; }
    }
}
