//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_TieuChi
    {
        public string ID { get; set; }
        public string MaTruong { get; set; }
        public string NamHoc { get; set; }
        public string NoiDung { get; set; }
        public string DiemManh { get; set; }
        public string DiemYeu { get; set; }
        public string KeHoach { get; set; }
        public Nullable<bool> TuDanhGia { get; set; }
    }
}
