//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_TieuChi_ChiSo
    {
        public string MaTruong { get; set; }
        public string ID { get; set; }
        public string ChiSo { get; set; }
        public string NamHoc { get; set; }
        public string NoiDung { get; set; }
        public string HienTrang { get; set; }
        public string YeuCau { get; set; }
        public string GoiY { get; set; }
    }
}
