//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_VanBan
    {
        public string ID { get; set; }
        public string MaTruong { get; set; }
        public string MaSo { get; set; }
        public string TrichYeu { get; set; }
        public Nullable<System.DateTime> NgayBanHanh { get; set; }
        public string CoQuanBanHanh { get; set; }
        public string LinkVanBan { get; set; }
        public string IDCapHoc { get; set; }
        public Nullable<bool> BoGiaoDuc { get; set; }
    }
}
