//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HT_GoiYMinhChung
    {
        public string GuiID { get; set; }
        public string IDChiSo { get; set; }
        public string MaMC { get; set; }
        public string TenMC { get; set; }
    }
}
