//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HT_TieuChuan
    {
        public string GuiID { get; set; }
        public Nullable<int> IDTieuChuan { get; set; }
        public string ThongTu { get; set; }
        public string IDCapHoc { get; set; }
        public string NoiDung { get; set; }
    }
}
